### ISSUE TITLE
Consider approaches to modifying TAQ2Chunks behavior

### ISSUE THREAD

**Issue by davclark** [dlab-projects/marketflow#20]
This would include how the data is chunked (rows, symbols) as well as where it's going.

- [Odo](http://odo.pydata.org/en/latest/index.html) can convert numpy chunks to whatever. [Blaze](http://blaze.readthedocs.org/en/latest/index.html) is a related technology that is good at slicing and dicing data.
- Martin Faasen's (author of lxml bindings for Python) wrote a generics library called [Reg](http://reg.readthedocs.org/en/latest/) inspired by [Zope Interfaces](http://docs.zope.org/zope.interface/). Probably overkill, but worth thinking about.
- Subclassing.

**Comment by deniederhut** [comment]
Can I have orientation/motivation for this issue?

**Comment by davclark** [comment]
Let's talk briefly on Monday. The short answer is that part of the benchmarking project will hopefully be working with different back-ends and conversion schemes. So, it'd be good to have a flexible system in place for converting data to different storage formats / databases and also different approaches to extracting / converting given a certain storage format.

**Comment by davclark** [comment]
I'm happy with the current approach. Future issues should mention specific technology to try.
