### ISSUE TITLE
H5_TIME is unsupported...

### ISSUE THREAD

**Issue by davclark** [dlab-projects/marketflow#31]
So, we shouldn't use it. This isn't a huge issue, and actually simplifies the logic of our code - no more special handling of a time column, it's _just_ a float64 in and HDF5 file.

I identified this [in the HDF5 docs](https://www.hdfgroup.org/HDF5/doc/RM/H5T/H5Tget_class.htm) after being referred there by h5py/h5py#360. See also [this](https://www.hdfgroup.org/hdf5-quest.html#time).

Not sure if this is related perhaps to dlab-projects/dlab-finance#60

**Comment by justinmccrary** [comment]
It may or may not be relevant, but the TAQ data are moving from recording
time in milliseconds to time in microseconds.  That change took place July
27, 2015.

**Comment by davclark** [comment]
I think I've noticed that move, as it broke things for later file versions.
It should still be fine to represent this as a float64 of seconds. a true
time64 would be more future proof, but we won't live that long.

On Tue, May 17, 2016 at 4:47 PM, justinmccrary <notifications@github.com>
wrote:

> It may or may not be relevant, but the TAQ data are moving from recording
> time in milliseconds to time in microseconds. That change took place July
> 27, 2015.
>
> On Tue, May 17, 2016 at 4:00 PM, Dav Clark <notifications@github.com>
> wrote:
>
> > So, we shouldn't use it. This isn't a huge issue, and actually simplifies
> > the logic of our code - no more special handling of a time column, it's
> > *just* a float64 in and HDF5 file.
> >
> > I identified this in the HDF5 docs
> > <https://www.hdfgroup.org/HDF5/doc/RM/H5T/H5Tget_class.htm> after being
> > referred there by h5py/h5py#360 <https://github.com/h5py/h5py/issues/360
> >.
> > See also this <https://www.hdfgroup.org/hdf5-quest.html#time>.
> >
> > Not sure if this is related perhaps to dlab-projects/dlab-finance#60
> > <https://github.com/dlab-projects/dlab-finance/issues/60>
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/dlab-projects/marketflow/issues/31>
> >
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/dlab-projects/marketflow/issues/31#issuecomment-219887167>
>



-- 
Dav Clark
Data Scientist
Berkeley D-Lab + BIDS
bead.glass
917-544-8408

**Comment by davclark** [comment]
Pretty easy fix. hdf5.py now updated. This has enabled Blaze / Dask and Blaze in particular is holy crap fast (at least on toy problems). Looking forward to testing with a bit more soon!
