### ISSUE TITLE
Create basic tests

### ISSUE THREAD

**Issue by davclark** [dlab-projects/marketflow#4]
For now, these will use actual TAQ data files that we can't legally share, so make a `.gitignore`d data directory for tests.

For now let's use [pytest](http://pytest.org/latest/).

@rdhyee knows some good files to use (so does @Jay4869).

cc @juanshishido

**Comment by davclark** [comment]
@juanshishido or @rdhyee if you can set up the basic scaffold to do a very basic test (including how to link to a TAQ file), @yangraymond can take over from there!

**Comment by davclark** [comment]
I need to see progress on this, so I'm taking over.

**Comment by rdhyee** [comment]
Please take it over -- I'm currently swamped and have no time to put into this work unfortunately.

**Comment by davclark** [comment]
From Matthew Brett:

> For nibabel what I did was add a series of submodules in a specified
location - <nibabel>/nibabel-data .  Then you can submodule update
init and let the submodules fail that you don't have authentication
for.  The tests test whether the data exist in the submodules and skip
otherwise.

> I was imagining a situation where you'd have a submodule for which you
had ssh checkout permission that you could checkout on your own
machine, but that you couldn't checkout on - say - travis-ci.

> Maybe you could give encrypted travis permissions to checkout your
proprietary data, running some minimal risk that someone could get to
it if they were clever.

> Skip logic used here :
> https://github.com/nipy/nibabel/blob/master/nibabel/tests/test_parrec_data.py

**Comment by davclark** [comment]
I think I'd lean towards git annex in this case. Especially because our data is quite proprietary and I'm not worried much about sharing...

**Comment by juanshishido** [comment]
@davclark I see the following changes (specific to this issue) in the repo:

* added `test-data`
* added `test_taq.py`

It looks like we need to add code to `test_taq.py`. Also, you mentioned that the data directory for tests (`test-data`, I'm assuming) needs to be added to `.gitignore`. Does this sound right for both of these points?

In terms of `test_taq.py`, _what_ should we be testing? I looked at https://github.com/BIDS-collaborative/dlab-finance/blob/master/basic-taq/test.py and it looks like it's just appending chunks to a DataFrame and then printing it. It's not verifying results against expectations. One such example could be checking the `shape` of the DataFrame for a specific file.

So, it would be helpful to get a clear description of what tests we should be writing.

**Comment by davclark** [comment]
Right - that's just a test that essentially tests that the module imports OK.

For now, let's keep all the tests in one file (until we have a good number), and generally, everything you said was right.

We should standardize on some files and just check that they compute known valid results. This could be done with a synthetic file ultimately, but for now, you can just choose a random TAQ file. Preferably one from after the switch to more columns and one before (I forget when the switch happened, but it's in the TAQ manual - do you have that?).

For now, we can assume that summary statistics are correct and be a bit circular - compute the answers with our code first, then make those answers part of the test (e.g., counts, means, etc.). At least we'll know when behavior changes.

If that's not clear, though, I could start specing out some tests and just write docstrings and make them raise a notimplemented error.

**Comment by davclark** [comment]
cc @jaysid95

**Comment by davclark** [comment]
Closing this, as the issue is essentially resolved, details remain, but I want to clean the tracker.
